image: google/cloud-sdk:alpine

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  PATH_ARTIFACTS_UI: us-central1-docker.pkg.dev/project-e8bfac80-29f9-47ec-b77/reports/ui
  PATH_ARTIFACTS_API: us-central1-docker.pkg.dev/project-e8bfac80-29f9-47ec-b77/reports/api
  VERSION_API: 0.2
  VERSION_UI: 0.2
  SERVICE_NAME_UI: reports-service-ui
  SERVICE_NAME_API: reports-service-api
  SERVICE_REGION: us-central1
  
stages:
  - build_deploy
  # - build
  # - deploy

build_deploy:
  stage: build_deploy
  script:
  - cp $GCP_SERVICE_ACC_KEY_REPORTS /tmp/keyfile.json
  - cp $ENV /tmp/api/.env
  - gcloud auth activate-service-account --key-file=/tmp/keyfile.json
  - gcloud config set project $CI_PROJECT_ID
  - gcloud builds submit --config=cloudbuild.yaml --substitutions=_PATH_ARTIFACTS_UI=$PATH_ARTIFACTS_UI,_PATH_ARTIFACTS_API=$PATH_ARTIFACTS_API,_VERSION_API=$VERSION_API,_VERSION_UI=$VERSION_UI,_SERVICE_NAME_UI=$SERVICE_NAME_UI,_SERVICE_NAME_API=$SERVICE_NAME_API,_SERVICE_REGION=$SERVICE_REGION .
  only:
    - main

