services:
  main:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - api/.env


  gradio:
    container_name: gradio_ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "8051:8051"
    depends_on:
      - main
  

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_collections:/qdrant/storage


