events {}

http {
    upstream qdrant_service {
        server qdrant:6333;
    }

    upstream gradio_service {
        server gradio:8051;
    }

    server {
        listen 80;

        # ---- QDRANT ROUTE ----
        location /qdrant/ {
            proxy_pass http://qdrant_service/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # remove /qdrant prefix before forwarding
            rewrite ^/qdrant/(.*)$ /$1 break;
        }

        # ---- YOUR UI ----
        location / {
            proxy_pass http://gradio_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}